parameters:
    database_driver:   pdo_mysql
    database_host:     tunnel.pagodabox.com
    database_port:     3306
    database_name:     listforks
    database_user:     inger
    database_password: a7bXocr3

    mailer_transport:  smtp
    mailer_host:       localhost
    mailer_user:       ~
    mailer_password:   ~

    locale:            en
    secret:            ThisTokenIsNotSoSecretChangeIt