_home:
    pattern: /
    defaults: 
        _controller: FrameworkBundle:Redirect:urlRedirect
        path: /lists
        permanent: true

_login:
    pattern: /accounts/login
    defaults: { _controller: ListForksBundle:Security:login }

_login_check:
    pattern: /accounts/login_check

_logout:
    pattern: /accounts/logout

accounts:
    type: rest
    resource: "@ListForksBundle/Controller/AccountsController.php"

lists:
    type: rest
    resource: "@ListForksBundle/Controller/ListsController.php"

_search:
    resource: "@ListForksBundle/Controller/SearchController.php"
    type:     annotation
    prefix:   /search


_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml






