_default:
    pattern:  /
    defaults: { _controller: ListForksBundle:Default:index }


_ListForks_home
    resource: "@AcmeListForksBundle/Controller/ListForksController.php"
    type:     annotation

_account:
    resource: "@ListForksBundle/Controller/AccountController.php"
    type:     annotation
    prefix:   /account

_list:
    resource: "@ListForksBundle/Controller/ListController.php"
    type:     annotation
    prefix:   /list

_search:
    resource: "@ListForksBundle/Controller/SearchController.php"
    type:     annotation
    prefix:   /search


_wdt:
    resource: "@WebProfilerBundle/Resources/config/routing/wdt.xml"
    prefix:   /_wdt

_profiler:
    resource: "@WebProfilerBundle/Resources/config/routing/profiler.xml"
    prefix:   /_profiler

_configurator:
    resource: "@SensioDistributionBundle/Resources/config/routing/webconfigurator.xml"
    prefix:   /_configurator

_main:
    resource: routing.yml






