jms_security_extra:
    secure_all_services: false
    expressions: true

security:
    encoders:
        ListForks\Bundle\Entity\Account:
            algorithm:  sha1
            iterations: 1
            encode_as_base64: false
        # Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        user_db:
            entity: { class: ListForksBundle:Account, property: username }
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/account/login$
            security: false

        create:
            pattern:  ^/account/create$
            security: false

        secured_area:
            pattern:    ^/
            form_login:
                check_path: /account/login_check
                login_path: /account/login
            logout:
                path:   /account/logout
                target: /account/login
            provider: user_db
            #anonymous: ~
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/account/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/account/create, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER }
        #- { path: ^/_internal/secure, roles: IS_AUTHENTICATED_ANONYMOUSLY, ip: 127.0.0.1 }
